version: "3.8"

services:
  php:
    build: .  # <--- Ahora construye la imagen desde tu Dockerfile
    container_name: ci4-php
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1

  db:
    image: postgres:15
    container_name: ci4-postgres
    environment:
      POSTGRES_USER: postgre
      POSTGRES_PASSWORD: Cc_34
      POSTGRES_DB: ferreteria
    ports:
      - "5432:5432"
      